---
# Role tasks

- name: assert platform is supported
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  assert:
    that:
      - distribution in win_domain_users_supported_distributions
      - >-
        ansible_facts.distribution_version
        is version(win_domain_users_supported_versions[distribution], ">=")
  tags:
    - role::win_domain_users
    - role::win_domain_users::check

- name: setup windows users
  loop: "{{ win_domain_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
  win_domain_user:
    account_locked: >-
      {{ user.account_locked | default(win_domain_users_defaults.account_locked) | default(omit) }}
    attributes: >-
      {{ user.attributes | default(win_domain_users_defaults.attributes) | default(omit) }}
    city: "{{ user.city | default(win_domain_users_defaults.city) | default(omit) }}"
    company: >-
      {{ user.company | default(win_domain_users_defaults.company) | default(omit) }}
    country: >-
      {{ user.country | default(win_domain_users_defaults.country) | default(omit) }}
    description: >-
      {{ user.description | default(win_domain_users_defaults.description) | default(omit) }}
    domain_password: >-
      {{ user.domain_password | default(win_domain_users_defaults.domain_password) | default(omit) }}
    domain_server: >-
      {{ user.domain_server | default(win_domain_users_defaults.domain_server) | default(omit) }}
    domain_username: >-
      {{ user.domain_username | default(win_domain_users_defaults.domain_username) | default(omit) }}
    email: >-
      {{ user.email | default(win_domain_users_defaults.email) | default(omit) }}
    enabled: >-
      {{ user.enabled | default(win_domain_users_defaults.enabled) | default(omit) }}
    firstname: >-
      {{ user.firstname | default(win_domain_users_defaults.firstname) | default(omit) }}
    groups: >-
      {{ user.groups | default(win_domain_users_defaults.groups) | default(omit) }}
    groups_action: >-
      {{ user.groups_action | default(win_domain_users_defaults.groups_action) | default(omit) }}
    name: >-
      {{ user.name | default(win_domain_users_defaults.name) | default(omit) }}
    password: >-
      {{ user.password | default(win_domain_users_defaults.password) | default(omit) }}
    password_expired: >-
      {{ user.password_expired | default(win_domain_users_defaults.password_expired) | default(omit) }}
    password_never_expires: >-
      {{ user.password_never_expires | default(win_domain_users_defaults.password_never_expires) | default(omit) }}
    path: >-
      {{ user.path | default(win_domain_users_defaults.path) | default(omit) }}
    postal_code: >-
      {{ user.postal_code | default(win_domain_users_defaults.postal_code) | default(omit) }}
    state: >-
      {{ user.state | default(win_domain_users_defaults.state) | default(omit) }}
    state_province: >-
      {{ user.state_province | default(win_domain_users_defaults.state_province) | default(omit) }}
    street: >-
      {{ user.street | default(win_domain_users_defaults.street) | default(omit) }}
    surname: >-
      {{ user.surname | default(win_domain_users_defaults.surname) | default(omit) }}
    update_password: >-
      {{ user.update_password | default(win_domain_users_defaults.update_password) | default(omit) }}
    upn: >-
      {{ user.upn | default(win_domain_users_defaults.upn) | default(omit) }}
    user_cannot_change_password: >-
      {{ user.user_cannot_change_password | default(win_domain_users_defaults.user_cannot_change_password) | default(omit) }}
  tags:
    - role::win_domain_users
