---

- name: Converge
  hosts: molecule_hosts
  tasks:
    - name: Create test users
      include_role:
        name: amtega.win_domain_users
        allow_duplicates: yes
      vars:
        win_domain_users_defaults:
          city: springfield
          company: evil_inc

        win_domain_users:
          - name: "{{ win_domain_users_tests_ad_user }}-a"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-a@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-a please erase me.
            password: "{{ win_domain_users_tests_ad_password }}_a"
            update_password: on_create
            firstname: "ansible test A"
            surname: test
            email: dont_ask@dont_respond.never.com
            account_locked: false
            attributes:
              telephoneNumber: 555-123456
            state: present
          - name: "{{ win_domain_users_tests_ad_user }}-b"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-b@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-b please erase me.
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}_b"
            update_password: on_create
            state: present
          - name: "{{ win_domain_users_tests_ad_user }}-c"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-c@"
                 + win_domain_users_tests_domain_name }}
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}_c"
            update_password: on_create
            state: present
            account_locked: no
            attributes:
              telephoneNumber: 555-123456
              EmployeeID: 15123456
              # extensionAttribute1: p_func
            city: Teruel
            company: Acme
            country: ES
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-c please erase me.
            email: dont_ask@dont_respond.never.com
            enabled: true
            firstname: Jane
            groups:
              - Domain Users
            groups_action: add
            # password_expired: no
            password_never_expires: false
            postal_code: 12345
            state_province: TE
            street: 13 Elm
            surname: Doe
            user_cannot_change_password: false
          - name: "{{ win_domain_users_tests_ad_user }}-d"
            state: absent
          - name: "{{ win_domain_users_tests_ad_user }}-e"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-e@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-e please erase me.
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}_e"
            update_password: on_create
            state: present
            overwrite: yes

    - name: 'Overwrite users:no'
      include_role:
        name: amtega.win_domain_users
        allow_duplicates: yes
      vars:
        win_domain_users:
          - name: "{{ win_domain_users_tests_ad_user }}-f"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-f@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-f please erase me.
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}_f"
            state: present
            overwrite: no
          - name: "{{ win_domain_users_tests_ad_user }}-g"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-g@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-g please erase me.
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}_g"
            state: present
            overwrite: no
