---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "WindowsServer-${INSTANCE_UUID:-1}"
    box: jborean93/WindowsServer2016
    groups:
      - molecule_hosts
      - molecule_hosts_windows
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule_hosts:
        hosts:
          WindowsServer-${INSTANCE_UUID:-1}:
            ansible_host: 127.0.0.1
            ansible_user: vagrant
            ansible_password: vagrant
            ansible_port: 55986
            ansible_connection: winrm
            ansible_winrm_transport: ntlm
            ansible_winrm_server_cert_validation: ignore
        vars:
          win_domain_users_no_log: no
          win_domain_users_tests_domain_name: test.local
          win_domain_users_tests_safe_mode_password: insecure_NDYJyQK8Mh7k3yr5
          win_domain_users_tests_ad_ou_name: Test
          win_domain_users_tests_ad_ou_base: "DC=test,DC=local"
          win_domain_users_tests_ad_ou: >-
            OU={{ win_domain_users_tests_ad_ou_name }},{{
            win_domain_users_tests_ad_ou_base }}
          win_domain_users_tests_ad_user: ansible_test_user
          win_domain_users_tests_ad_password: ansible_test_NDYJyQK8Mh7k3yr5

verifier:
  name: ansible
