---

- name: Prepare
  hosts: all
  gather_facts: yes
  tasks:
    - wait_for_connection:

    - name: install ad
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: ad_install_result
      until: ad_install_result is not failed
      retries: 30
      delay: 15

    - name: Ensure the RSAT-AD-PowerShell feature is installed
      win_feature:
        name:
          - RSAT-AD-PowerShell
        state: present
      register: ad_feature_result

    - name: install domain
      win_domain:
        dns_domain_name: '{{ win_domain_users_tests_domain_name }}'
        safe_mode_password: '{{ win_domain_users_tests_safe_mode_password }}'
      register: domain_install_result
      until: domain_install_result is successful
      retries: 30
      delay: 15

    - name: reboot server
      win_reboot:
        msg: "Installing AD. Rebooting..."
        pre_reboot_delay: 15
      when: >-
        ad_install_result.reboot_required
        or ad_feature_result.reboot_required
        or domain_install_result.changed

    - wait_for_connection:

    - name: Win ping
      win_ping:

    # TODO: win_wait_for_process: Search for the process needed
    #       for New-ADOrganizationalUnit
    - name: Create OU
      win_shell: >
        $ou = Try {
        Get-ADOrganizationalUnit
        -Identity "{{ win_domain_users_tests_ad_ou }}" }
        Catch { $null }
        If (-Not $ou) {
        New-ADOrganizationalUnit
        -Name "{{ win_domain_users_tests_ad_ou_name }}"
        -Path "{{ win_domain_users_tests_ad_ou_base }}" }
      register: ou_creation_result
      until: ou_creation_result is successful
      retries: 30
      delay: 15

    - name: Populate test users
      include_role:
        name: amtega.win_domain_users
      vars:
        win_domain_users:
          - name: "{{ win_domain_users_tests_ad_user }}-d"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-d@"
                 + win_domain_users_tests_domain_name }}
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}_d"
            state: present
          - name: "{{ win_domain_users_tests_ad_user }}-e"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-e@"
                 + win_domain_users_tests_domain_name }}
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}e"
            state: present
          - name: "{{ win_domain_users_tests_ad_user }}-f"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-f@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-f please erase me.
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}f"
            state: present
          - name: "{{ win_domain_users_tests_ad_user }}-g"
            upn: >-
              {{ win_domain_users_tests_ad_user
                 + "-g@"
                 + win_domain_users_tests_domain_name }}
            description: >-
              Test user {{ win_domain_users_tests_ad_user }}-g please erase me.
            path: "{{ win_domain_users_tests_ad_ou }}"
            password: "{{ win_domain_users_tests_ad_password }}g"
            state: present
