---
- name: Prepare
  hosts: all
  gather_facts: yes
  tasks:

    - name: Ping
      win_ping:

    - name: install ad
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: ad_install_result

    - name: Ensure the RSAT-AD-PowerShell feature is installed
      win_feature:
        name:
          - RSAT-AD-PowerShell
        state: present
      register: ad_feature_result

    - name: install domain
      win_domain:
        dns_domain_name: '{{ win_domain_users_tests_domain_name }}'
        safe_mode_password: '{{ win_domain_users_tests_safe_mode_password }}'
      register: domain_install_result

    - name: reboot server
      win_reboot:
        msg: "Installing AD. Rebooting..."
        pre_reboot_delay: 15
      when: >-
        ad_install_result.reboot_required
        or ad_feature_result.reboot_required
        or domain_install_result.changed

    - name: Win ping
      win_ping:

    - name: Create OU
      win_shell: >
        New-ADOrganizationalUnit
        -Name "{{ win_domain_users_tests_ad_ou_name }}"
        -Path "{{ win_domain_users_tests_ad_ou_base }}"
